Edited to build images for tmeslogger appliance

diff --git a/scripts/firstrun b/scripts/firstrun
--- a/scripts/firstrun
+++ b/scripts/firstrun
@@ -19,68 +19,77 @@ MEMTOTAL=$(awk 'BEGIN { printf "%.0f\n", '$(grep MemTotal /proc/meminfo | awk '{
 set -e
 
 do_expand_rootfs(){
-        device="/dev/mmcblk0"
-        ((echo d; echo n; echo p; echo 1; echo ; echo; echo w;) | fdisk $device)>/dev/null
-return 0
+	device="/dev/mmcblk0"
+	((echo d; echo n; echo p; echo 1; echo ; echo; echo w;) | fdisk $device)>/dev/null
+	return 0
 }
 
 case "$1" in
-  start)
-            reboot=false
-                echo ""
-                toilet -f standard "first run"
-                # if we have 1G ram reduce RAMLOG size 
-				if (($MEMTOTAL <= 1)); then
-						if [ -f "/etc/default/ramlog" ]; then
-                        sed -e 's/TMPFS_RAMFS_SIZE=512m/TMPFS_RAMFS_SIZE=256m/g' -i /etc/default/ramlog
-						fi
-						# for cubieboard disable some services
-                        if [ -f "/boot/cubieboard2.bin" ]; then
-                                /sbin/insserv -r brcm40183-patch
-                                /sbin/insserv -r disable_led.sh
-                        fi
-                fi
-                # Remove lirc for Lime boards
-                if [ -f "/boot/lime.bin" ] || [ -f "/boot/lime2.bin" ]; then
-                        /sbin/insserv -r lirc        
-                fi
-                #
-                echo "This process takes around one minute to finish..."
-                #NEWMAC=00:01:43:`openssl rand -hex 3 | sed 's/\(..\)/\1:/g; s/.$//'`
-                #sed -e 's/ether/ether '$NEWMAC'/g' -i /etc/network/interfaces.default
-                #sed -e 's/ether/ether '$NEWMAC'/g' -i /etc/network/interfaces.hostapd
-                # Cubietruck exception
-		                # if HDMI is attached during boot, set default screen output to HDMI
-                if [ -n "$(dmesg | grep ParseEDID)" ] && [ -f "/boot/cubietruck.bin" ]; then
-                        bin2fex /boot/cubietruck.bin /tmp/tmp.fex
-                        sed -e 's/screen0_output_type.*/screen0_output_type     = 3/g' -i /tmp/tmp.fex
-                        fex2bin /tmp/tmp.fex /boot/cubietruck.bin
-                fi
-                rm -f /etc/ssh/ssh_host*
-                dpkg-reconfigure openssh-server 
-                set +e
-                if [ "$(fping 8.8.8.8 | grep alive)" != "" ]; then
-                        echo "Updating packages list..."
-                        apt-get update >/dev/null 2>&1
-                fi
-                #
-                echo "Expanding rootfs..."
-                if do_expand_rootfs;then
-                        echo "Expanding rootfs success, rebooting automatically." 
-                        /sbin/insserv resize2fs
-                        reboot=true
-                else
-                        echo "Expanding rootfs has failed, see log files." 
-                fi
-                /sbin/insserv -r firstrun
-		if $reboot;then
+	start)
+		reboot=false
+		echo ""
+		toilet -f standard "first run"
+		
+		# if we have 1G ram reduce RAMLOG size 
+		if (($MEMTOTAL <= 1)); then
+			if [ -f "/etc/default/ramlog" ]; then
+				sed -e 's/TMPFS_RAMFS_SIZE=512m/TMPFS_RAMFS_SIZE=256m/g' -i /etc/default/ramlog
+			fi
+		fi
+		
+		echo "Installing Labjack Exodriver..."
+		cd /root/exodriver-master
+		./install.sh
+		cd /
+		rm -r /root/exodriver-master
+		
+		echo "Installing Labjack python library..."
+		cd /root/LabJackPython-master
+		python setup.py install
+		cd /
+		rm -r /root/LabJackPython-master
+		
+		echo "Installing pyA20..."
+		cd /root/pyA20-0.2.0/
+		python setup.py install
+		cd /
+		rm -r /root/pyA20-0.2.0
+		
+		echo "Generating SSL cert..."
+		echo -e "DE\nNRW\nWuelfrath\nTMES UG\nIT\ninfo@tmes.de\n" | openssl req -x509 -newkey rsa:2048 -keyout /etc/nginx/nginx.ssl.key -out /etc/nginx/nginx.ssl.crt -days 3650 -nodes
+		
+		echo "Generating cookie secret..."
+		SLIM_SECRET=$(< /dev/urandom tr -dc A-Za-z0-9 | head -c${1:-32};echo;)
+		sed -e "/secret/c\                'secret' => '$SLIM_SECRET'," -i /usr/share/nginx/www/index.php
+		
+		echo "Generating SSH key..."
+		echo "This process takes around one minute to finish..."
+		rm -f /etc/ssh/ssh_host*
+		dpkg-reconfigure openssh-server 
+		set +e
+		
+		echo "Installing to SATA..."
+		/bin/bash /root/sata-install.sh
+		
+		#expanding rootfs
+		echo "Expanding rootfs..."
+		if do_expand_rootfs; then
+			echo "Expanding rootfs success, rebooting automatically." 
+			/sbin/insserv resize2fs
+			reboot=true
+		else
+			echo "Expanding rootfs has failed, see log files." 
+		fi
+		
+		/sbin/insserv -r firstrun
+		if $reboot; then
 			/sbin/reboot
 		fi
-        ;;
-  *)
-        echo "Usage: $N {start}" >&2
-        exit 1
-        ;;
+		;;
+	*)
+		echo "Usage: $N {start}" >&2
+		exit 1
+		;;
 esac
 
 exit 0
